### PR TITLE
NEW: adds 2D scatterplot

### PR DESCRIPTION
**Pull request by lizgehret**
Goals for the first working draft:

- [x] Accepts metadata-like inputs (anything that can be transformed into a DF)
- [x] Numeric `data` required, categorical `metadata` optional (used for color-coding)
- [x] 2 dimensional
~~- [ ] Support for flipping axes interactively~~ _no longer needed for this scope_
~~- [ ] Support for inverting data interactively~~ _no longer needed for this scope_

### CODE REVIEW

**Comment by lizgehret** [comment]
First refactored draft from the following spec via vega editor:

https://vega.github.io/editor/#/gist/60892220e4e76e84739b2a756080852e/vizard_scatter.json

**Comment by nbokulich** [comment]
hey @lizgehret — awesome! I look forward to trying out a stable draft whenever it is ready.

I just have a quick comment/question for now: why do you split `data` and `metadata` into two separate inputs? I wonder, since both are `Metadata` objects. Technically couldn't you just have one metadata input and the user can select what is displayed on the x and y axes? A user could always merge multiple metadata objects if they want to plot, e.g., feature abundance vs. some sample metadata.

It would also be cool to allow a user to select the X and Y axis data interactively, instead of selecting these as params... I can open a feature request for this if you would like to save that for the future. Otherwise, given the current operation it seems like data/metadata should rather be numeric metadata columns... Then QIIME 2 can enforce that valid column names are being used.

**Comment by lizgehret** [comment]
> hey @lizgehret — awesome! I look forward to trying out a stable draft whenever it is ready.
> 
> I just have a quick comment/question for now: why do you split `data` and `metadata` into two separate inputs? I wonder, since both are `Metadata` objects. Technically couldn't you just have one metadata input and the user can select what is displayed on the x and y axes? A user could always merge multiple metadata objects if they want to plot, e.g., feature abundance vs. some sample metadata.
> 
> It would also be cool to allow a user to select the X and Y axis data interactively, instead of selecting these as params... I can open a feature request for this if you would like to save that for the future. Otherwise, given the current operation it seems like data/metadata should rather be numeric metadata columns... Then QIIME 2 can enforce that valid column names are being used.

Hey @nbokulich! That's a great question - my thought process for that was that we'd allow a metadata-like object (essentially something that can be transformed to/from a dataframe, like ordination results, alpha diversity, etc) that would contain numeric/continuous values. This would be the `data`, and would be required. For the `metadata`, this would be optional and could contain another metadata-like object (actual metadata, or a dataframe object that contains at least one categorical/discrete column). This is what would create the colors in the scatter, but wouldn't be required for basic functionality (i.e. just plotting two continuous values).

With that being said, this could definitely just take one metadata object that contains all of the information above (i.e. merged alpha diversity w/associated metadata, etc) and then just accept particular columns from the user to identify what they'd like to visualize. I'm open to whatever seems like the most flexible option - cc @gregcaporaso and @ebolyen.

Re: x & y being selected interactively - I'm sure there's a way to do that in vega (similar to how we have drop downs for metadata columns in taxa barplot, etc). I think opening up an issue would be perfect - I'm going to finish up this draft, and then can iterate from there based on what we think makes the most sense to add/change!

**Comment by gregcaporaso** [comment]
@lizgehret, I agree that it would be nice to take a single `qiime2.Metadata` as input, and then let the user interactively select which continuous columns to plot on the x- and y-axes, and which continuous or discrete columns to use for coloring. 

[Here's an example](https://vega.github.io/vega/examples/scatter-plot-null-values/) I found in the vega gallery showing how to interactively select the data to plot on two axes of a scatterplot, and this is the example that we looked at where a user can [pass two metadata objects as input](https://docs.qiime2.org/2023.9/tutorials/metadata/#merging-metadata) to a [visualizer](https://github.com/qiime2/q2-metadata/blob/5ac387755caa3c006b0c18f9d4d68ea685590c9c/q2_metadata/_tabulate.py).

**Comment by lizgehret** [comment]
> @lizgehret, I agree that it would be nice to take a single `qiime2.Metadata` as input, and then let the user interactively select which continuous columns to plot on the x- and y-axes, and which continuous or discrete columns to use for coloring.
> 
> [Here's an example](https://vega.github.io/vega/examples/scatter-plot-null-values/) I found in the vega gallery showing how to interactively select the data to plot on two axes of a scatterplot, and this is the example that we looked at where a user can [pass two metadata objects as input](https://docs.qiime2.org/2023.9/tutorials/metadata/#merging-metadata) to a [visualizer](https://github.com/qiime2/q2-metadata/blob/5ac387755caa3c006b0c18f9d4d68ea685590c9c/q2_metadata/_tabulate.py).

Hey all - I've modified this to utilize exactly Metadata as an input, and should be able to implement the interactive selection for x and y fairly easily from here (that's a nice example @gregcaporaso).

Main updates in terms of the inputs are that the x & y axes are numeric MD columns, and we'll also accept an optional categorical column, which will color-code the points according to their 'group'.

**Comment by gregcaporaso** [comment]
@lizgehret, is it possible to allow interactive selection of the categorical column for coloring too (or maybe all the columns for coloring - and default to continuous or discrete color scales based on the metadata column type)?

**Comment by lizgehret** [comment]
> @lizgehret, is it possible to allow interactive selection of the categorical column for coloring too (or maybe all the columns for coloring - and default to continuous or discrete color scales based on the metadata column type)?

Yep, that should be possible re: still retaining the coloring with respect to the drop down (currently working on that now). The main thing that would become more complex is if a user chooses a numeric MD col from the drop down, the legend would look pretty crazy (since it would group each numeric value into a legend category). I'm not sure if we want to allow that or not.

**EDIT**: I've updated the drop down so that it only permits categorical metadata columns to be selected, which should solve this problem.

**Comment by lizgehret** [comment]
Hey @gregcaporaso @nbokulich! I've got a first working draft for you both to try out when you have the chance.

One thing I haven't implemented is the interactive x&y axes - I was thinking it could be good for users to intentionally select MD columns when they're creating the viz, and I've added validation to ensure the inputs they're selecting are both numeric. Open to thoughts about that, and we can definitely play around with adding in the interactivity for x&y (with the restriction that we're only allowing numeric columns for those - similar to how the group dropdown only allows for categorical columns).

I've attached a toy dataset I created for testing - feel free to use this and/or any other MD file you'd like.
[cars.txt](https://github.com/qiime2/q2-vizard/files/15268602/cars.txt)

**Comment by lizgehret** [comment]
~~**UPDATE**: i found a bug while using the moving pictures dataset - it looks like not all points are being plotted. will work on a fix for this!~~

Not a bug, all points were being plotted - there were just only 5 unique xy locations for the moving pictures metadata. So this is ready for a first round review!

**Comment by gregcaporaso** [comment]
Hey @lizgehret, This looks really nice! 

A few things I think would be nice to address for version 1:
 - I do think it would make this more useful if the x and y measures were optional (they become the default/starting value(s) if provided), and let the user choose what is plotted on each axis from numeric metadata columns within the visualization. Already I have some things I'd like to look at with this, but it would require the generation of a bunch of different plots. 
 - Could the weight/width of the outline of the points be increased? They are pretty light in the plot. 
 - "CategoricalMetadataColumn" in the figure would be more self-documenting if it was replaced with "Color points by:" (or something like that). Additionally, could we connect a parameter that would set the default (starting) coloring of the points as a user-specified categorical metadata column? 
 - I could see us wanting to add a 3D scatterplot in the future. Do you think it would make sense to call this something like scatterplot-2d, to make way for a scatterplot-3d in the future? I don't have strong feelings about this one. 
 
Other things that could be issues that are addressed later:
 - What do you think of additionally giving the user control over the shape of the points based on categorical metadata, such that one category could represent the shape and another the color? 
 - Could we integrate control of the color palette in the visualization? 
 - Could we integrate an interactive legend, as in [this example](https://vega.github.io/vega/examples/interactive-legend/)? 
 - It'd be neat to (optionally) have histograms on the top and left, showing the distribution of points on the x and y axes, respectively. For example, see [here](https://blogs.sas.com/content/graphicallyspeaking/files/2014/12/scatter_and_hist_border.png). (This is a nice-to-have-someday request, rather than anything that would need to be addressed any time soon.)

**Comment by lizgehret** [comment]
Thanks for all of this feedback @gregcaporaso, this is all very helpful! Requests for v1 are addressed below.

 

- [x] I do think it would make this more useful if the x and y measures were optional (they become the default/starting value(s) if provided), and let the user choose what is plotted on each axis from numeric metadata columns within the visualization. Already I have some things I'd like to look at with this, but it would require the generation of a bunch of different plots.

   **Sounds good, I can do that! I'll have x&y handled the same as the color drop-down, just with numeric columns.**

 - [x] Could the weight/width of the outline of the points be increased? They are pretty light in the plot.
   **Definitely - I'd like to play around with the styling a bit more, and this was one of the things I wanted to change as well.**

 - [x] "CategoricalMetadataColumn" in the figure would be more self-documenting if it was replaced with "Color points by:" (or something like that).
   ~~**Works for me, I'll update that!**~~ **EDIT**: _the titles for signals need to be in JavaScript format, so I've updated this to `ColorBy`. LMK if you'd prefer something else (it just can't have spaces/special chars)._

 - [x] Additionally, could we connect a parameter that would set the default (starting) coloring of the points as a user-specified categorical metadata column?
   **Definitely - I actually had this hooked up originally, and then ended up removing it.**

 - [x] I could see us wanting to add a 3D scatterplot in the future. Do you think it would make sense to call this something like scatterplot-2d, to make way for a scatterplot-3d in the future? I don't have strong feelings about this one.
   **Works for me!**

**Comment by lizgehret** [comment]
Hey @gregcaporaso, all of your v1 review comments have been addressed! I tweaked some styling elements as well to make things look a bit better - let me know what you think about the updates when you have the chance to take a look. @nbokulich let me know if there's anything else you'd like to see outside of @gregcaporaso's feedback!

**Comment by gregcaporaso** [comment]
This is looking really good to me @lizgehret! 

One other comment: I think the current `--p-group-measure` should be `--p-color-by-group`, or something like that, to set the stage for connecting other shapes/etc in the future. 

[Here's](https://view.qiime2.org/visualization/?src=https://www.dropbox.com/scl/fi/l76or6ts0bz3ueztelttd/viz.qzv?rlkey=v37s02cdzp5dp56n46p3rtdch) a plot I'm looking at based on the *Moving Pictures* data. 

I think this is basically ready for merge whenever - since this is all pre-release we can always get other changes in. @nbokulich, what do you think? Are there edits you'd like to see in there before merge?

**Comment by lizgehret** [comment]
Thanks @gregcaporaso! That param name change makes sense to me - just pushed up those updates. @nbokulich let me know if there's anything else you'd like to see in this version - otherwise I'll get tests added before merging.

**Comment by nbokulich** [comment]
This looks great @lizgehret thanks! I am already planning some feature requests 😉 but have no requests for changes to the current PR (I only did a user test with a couple datasets, did not review the code)

**Comment by lizgehret** [comment]
Awesome, thank you both! Will add some tests and get this merged!

**Comment by lizgehret** [comment]
FYI I merged this PR but am still making commits to the `scatterplot` branch with a couple of tweaks & adding unit tests. once that's done i'll merge into `dev`.

**Pull request merged**
